ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

ENV CFLAGS="-O1 -g3 -fno-omit-frame-pointer -fsanitize=address,undefined"
ENV CXXFLAGS="-O1 -g3 -fno-omit-frame-pointer -fsanitize=address,undefined"
ENV LDFLAGS="-fsanitize=address,undefined"
