SM_DIR = "/usr/local/lib/flexric/"

Name = "xApp"
NearRT_RIC_IP = "10.54.0.10"
E42_Port = 36422

Sub_ORAN_SM_List = (
    {
        name = "KPM",
        time = 1000,
        format = 1,
        ran_type = "ngran_gNB_DU",
        actions = (
            { name = "DRB.UEThpDl" },
            { name = "RRU.PrbTotDl" }
        )
    }
)

xApp_DB = {
    enable = "OFF"
    ip = "127.0.0.1"
    dir = "/tmp/"
    filename = "xapp-kpm.db"
    username = ""
    password = ""
}
